'use client';

import Image from 'next/image';
import { useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Database, ShieldCheck } from 'lucide-react';

const trail = [
  { era: 'THE ORIGINAL QUESTION', title: 'What should one person build as AI becomes more powerful?', clue: 'We started by looking for a “holy grail” one-person business. But apps built only around today’s model limits could disappear when the next model improved.', answer: 'The durable opportunity had to sit beneath intelligence—not depend on intelligence staying weak.', next: 'What becomes harder to ignore as intelligence makes more activity accessible?' },
  { era: 'LOOKING UNDERNEATH AI', title: 'Powerful intelligence still does not directly experience the world.', clue: 'AI can reason over records, sensors, documents, and tools. It cannot create a missing observation, prove that a physical event occurred, or know that several sources share one hidden dependency.', answer: 'The scarce thing might be a defensible connection between a claim and reality.', next: 'Would that problem survive if AI became one hundred times more capable?' },
  { era: 'THE 100× TEST', title: 'Remove intelligence as the bottleneck.', clue: 'Across lending, healthcare, logistics, infrastructure, robotics, and defense, better reasoning reduced uncertainty—but unobserved, stale, manipulated, or dependent evidence still remained.', answer: 'Inference can improve an estimate. It cannot manufacture external evidence.', next: 'Where does this residual problem become easiest to see?' },
  { era: 'THE STRESS ENVIRONMENT', title: 'IoBT exposed the failure pattern.', clue: 'In unrelated real failures, missing confirmation was treated as permission. Multiple signals were counted as independent even when they shared a sensor, clock, power supply, network, or model.', answer: 'The deeper failure was information loss: UNKNOWN, provenance, freshness, and dependence disappeared before action.', next: 'Can we stop certainty from growing without new evidence?' },
  { era: 'THE WORKING MECHANISM', title: 'Keep evidence attached all the way to action.', clue: 'We built a deterministic Claim–Evidence–Action contract, froze scenarios, attacked the evaluator, and found the same weakness inside our own prototype: metadata could be missing, wrong, or fabricated.', answer: 'A gate is useful only if the evidence entering it is grounded and inspectable. Reality Audit became an internal verification process—not the final product.', next: 'What product becomes stronger as agents take more real actions?' },
  { era: 'TWO IDEAS, ONE SPINE', title: 'Reality Data and Agent Economics met at the same boundary.', clue: 'One direction was machine-readable reality: fresh, specific, trustworthy claims. The other was agent spending control: authorize cost before action and count value only after an accepted outcome.', answer: 'Both require one Evidence Graph: claim → evidence → source → action → outcome → economic consequence.', next: 'What are we building now?' },
  { era: 'THE CURRENT BUILD', title: 'A Reality Control Plane for agent action.', clue: 'Reality Data evaluates facts machines depend on. Agent Economics controls resource commitments and binds them to verified outcomes. The internal audit keeps unsupported certainty from passing between them.', answer: 'This is a functioning V1, not a finished company. Authentication, richer dependency semantics, external integrations, and commercial demand still need real-world proof.', next: 'Can an outside operator connect one real workflow and show that this changes a consequential decision?' },
];

export default function DiscoveryStory() {
  const [step, setStep] = useState(0);
  const chapter = trail[step];
  return <main className="discovery-app">
    <nav className="discovery-nav"><a href="/data" className="discovery-mark"><span>R</span>Reality</a><div><a href="/data"><Database size={16}/>Reality Data</a><a href="/economics"><ShieldCheck size={16}/>Agent Economics</a><a className="active" href="/discovery"><BookOpen size={16}/>Discovery Story</a></div><a href="https://github.com/guardian-coder/reality" target="_blank" rel="noreferrer">Open research ↗</a></nav>
    <section className="discovery-stage">
      <div className="discovery-progress"><span>DISCOVERY {String(step + 1).padStart(2,'0')} / {String(trail.length).padStart(2,'0')}</span><div>{trail.map((_,i)=><i key={i} className={i <= step ? 'active' : ''}/>)}</div></div>
      <article className="discovery-card" key={step}><small>{chapter.era}</small><h1>{chapter.title}</h1><div className="discovery-reveal"><section><span>WHAT WE SAW</span><p>{chapter.clue}</p></section><section><span>WHAT IT CHANGED</span><p>{chapter.answer}</p></section></div><div className="discovery-question"><span>THE NEXT QUESTION</span><p>{chapter.next}</p></div><footer><button disabled={step === 0} onClick={()=>setStep(step-1)}><ArrowLeft size={17}/>Back</button><button disabled={step === trail.length-1} onClick={()=>setStep(step+1)}>{step === trail.length-1 ? 'You are here' : 'Follow the clue'}<ArrowRight size={17}/></button></footer></article>
      <aside className="discovery-scout"><div><Image src="/reality-scout.png" alt="Reality Scout robotic companion" fill priority sizes="220px"/></div><p><b>{step === trail.length-1 ? 'The frontier is open.' : 'One answer opens the next question.'}</b><span>{step === trail.length-1 ? 'The next proof must come from a real external workflow.' : 'Move forward when the current discovery is clear.'}</span></p></aside>
    </section>
    <section className="discovery-destination"><small>WHAT EXISTS NOW</small><h2>Two working pillars. One evidence spine.</h2><div><a href="/data"><Database size={21}/><span><b>Reality Data</b><small>Turn external evidence into inspectable machine claims.</small></span><ArrowRight size={18}/></a><a href="/economics"><ShieldCheck size={21}/><span><b>Agent Economics</b><small>Control agent spend and count only verified outcomes.</small></span><ArrowRight size={18}/></a></div></section>
  </main>;
}
